"""Rebuild the source-only normative-axis report without model calls."""

from simulacria.selection.axis import (
    digest,
    hit_summary,
    length_summary,
    load_corpus,
    match_statutes,
    paired_lengths,
    verify_statutory_snapshot,
    virtue_failures,
)
from simulacria.selection.pools import PROJECT_ROOT


def table(rows: list[dict]) -> str:
    columns = list(rows[0])
    lines = ["| " + " | ".join(columns) + " |", "| " + " | ".join("---" for _ in columns) + " |"]
    lines.extend(
        "| " + " | ".join(str(r[c]).replace("|", "\\|") for c in columns) + " |" for r in rows
    )
    return "\n".join(lines)


def main() -> None:
    root = PROJECT_ROOT
    philosophy_path = root / "corpus/philosophy_v1.yaml"
    statutory_path = root / "corpus/statutory_axis_v1.yaml"
    philosophy = load_corpus(philosophy_path)
    baseline = load_corpus(statutory_path)
    verify_statutory_snapshot(baseline, root)
    matched = match_statutes(philosophy, baseline)
    failures = virtue_failures(philosophy)
    report = [
        "# Normative-axis source audit — 2026-09-11",
        (
            "Generated by `python scripts/report_normative_axis.py`. No model calls. "
            "These are lexical selection outputs, not direction measurements."
        ),
        (
            f"Philosophy corpus SHA-256: `{digest(philosophy_path)}`.\n\n"
            f"Statutory snapshot SHA-256: `{digest(statutory_path)}`.\n\n"
            f"Marker source SHA-256: `{digest(root / 'simulacria/selection/markers.py')}`."
        ),
        "## Lengths against the full specimen baseline",
        (
            "Target band: the minimum–maximum of the statutory row below, in Unicode "
            "characters including spaces/newlines. Inclusive quartiles. Means are close; "
            "ranges are narrower for the constructed duties. Matching is approximate."
        ),
        table(length_summary(philosophy + baseline)),
        "## Matched statutory subset",
        table(length_summary(matched)),
        table(
            [{k: r[k] for k in ("passage_id", "matched_to", "length_difference")} for r in matched]
        ),
        "## Paired duty lengths",
        table(paired_lengths(philosophy)),
        "## Marker occurrences and passage coverage",
        (
            "Overlapping matches are retained. Coverage counts passages, not occurrences. "
            "The full statutory baseline was previously selected using these markers; "
            "statutory coverage cannot independently validate the instrument."
        ),
        table(hit_summary(philosophy + matched)),
        "## Virtue failures",
        f"Passages with any marker hit: {len(failures)}.",
    ]
    for row in failures:
        report.extend([f"### {row['passage_id']}", row["text"], table(row["hits"])])
    report.extend(
        [
            (
                "The `om` in the ambition sketch introduces the object of a conception, "
                "not a condition. Keep it as an observed false positive. The promise pair "
                "also contains nonconditional `om` in `försäkran om god vilja`."
            ),
            "## Categorical failures and philosophical limits",
            (
                "Every categorical text contains `utan undantag`; the `undantag` regex fires "
                "without handling negation. Controls match both `dock` and `gäller inte`, "
                "which must not be mistaken for two semantic exceptions. No marker was changed."
            ),
            (
                "The duties deliberately have actor/object scope but no intended escape clause. "
                "Consent, conversational respect and confidentiality are the most contestable "
                "Kantian constructions; all require independent review before a model experiment. "
                "The confidentiality case concerns voluntarily accepted trust, not a claim that "
                "Kant mandates silence in every situation. The control exception for respect is "
                "deliberately coarse and may be judged conceptually weak. This is review material, "
                "not a validated philosophical benchmark."
            ),
            "## Repository review implications",
            (
                "`direction` and the loop remain absent. Insertion requires a real annotated pair "
                "and a contract distinguishing an added exception from a changed qualifier. "
                "DIRECTION.md case 9 also needs resolution: its two described changes each read "
                "as loosening under the preceding cases, yet its expected vector contains one "
                "tightening. This task does not rewrite that specification or implement around it."
            ),
            (
                "The frozen Databricks path, library extraction, ceiling investigation and specimen "
                "sheet were left unchanged. No dependency installation, external service changes, "
                "model calls, commit or push was performed. The pre-run predictions remain a draft "
                "until committed with complete run parameters."
            ),
            "## Verification",
            (
                "The notebook was executed with stored outputs. The new tests validate corruption "
                "failures, missing pairs, UTF-8 text, exact specimen text/URL provenance, stable "
                "matching, retained false positives and verbatim marker offsets. Full-suite status "
                "is recorded in CONTINUITY.md; the existing determinacy fixture failure remains. "
                "No generation results, human agreement or normative classifier were verified."
            ),
        ]
    )
    destination = root / "review/2026-09-11/NORMATIVE_AXIS_RESULTS.md"
    destination.write_text("\n\n".join(report) + "\n", encoding="utf-8")
    print(destination.relative_to(root))


if __name__ == "__main__":
    main()
